# Generated by Django 4.2.2 on 2023-06-26 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='KafedraTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=150, verbose_name="O'qituvchi (FISH)")),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('birthday', models.DateField(verbose_name='Tugilgan sana')),
                ('graduated_education', models.CharField(max_length=200, verbose_name="Ta'lim olgan oliy talim")),
                ('degree', models.CharField(max_length=100, verbose_name='Daraja')),
                ('direction', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mutaxasisligi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ustoz haqida...')),
                ('teacher_images', models.ImageField(upload_to='teacher_images/', verbose_name="O'qituvchi rasmi")),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklagan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraTeachersUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('image', models.ImageField(upload_to='update/', verbose_name='Rasmi')),
                ('teacher_updated_time', models.DateField(verbose_name='Malaka oshirish sanasi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedrateacher', verbose_name="O'qituvchi ismi (FISH)")),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraSince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Ilmiy yo'nalish nomi")),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('description', models.TextField(help_text="Mana shu yo'nalish haqida ma'lumot", verbose_name='Matni')),
                ('image', models.ImageField(upload_to='since/', verbose_name='Rasmi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('body', models.TextField(verbose_name='Yangilik matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images', verbose_name='Rasm')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklagan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tashkilot yoki universitet nomi', max_length=250, verbose_name='Nomi')),
                ('district', models.CharField(help_text='hamkorlik qaysi soha boyicha', max_length=250, verbose_name="Hamkorlik yo'nalishi")),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('description', models.TextField(help_text="Mana shu hamkorlik haqida ma'lumot", verbose_name='Matni')),
                ('image', models.ImageField(upload_to='international/', verbose_name='Rasmi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Garnt nomi')),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('description', models.TextField(help_text="Mana shu grant haqida ma'lumot", verbose_name='Matni')),
                ('image', models.ImageField(upload_to='grant/', verbose_name='Rasmi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
        migrations.CreateModel(
            name='KafedraCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=250, verbose_name='Url manzil :) ')),
                ('description', models.TextField(help_text="Mana shu Manaviy-ma'rifiy ish haqida ma'lumot", verbose_name='Matni')),
                ('image', models.ImageField(upload_to='cultural/', verbose_name='Rasmi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuklangan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='Holati')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='kafedra.kafedracategory', verbose_name='Kafedra')),
            ],
            options={
                'ordering': ['-published_time'],
            },
        ),
    ]
